package ahtewlg7.utimer.db.autogen;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import ahtewlg7.utimer.db.converter.DateTimeTypeConverter;
import ahtewlg7.utimer.db.converter.GtdStateConverter;
import ahtewlg7.utimer.db.entity.TaskEntityGdBean;
import ahtewlg7.utimer.enumtype.GtdState;
import org.joda.time.DateTime;

import ahtewlg7.utimer.db.entity.ActionEntityGdBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ACTION_ENTITY".
*/
public class ActionEntityGdBeanDao extends AbstractDao<ActionEntityGdBean, Long> {

    public static final String TABLENAME = "ACTION_ENTITY";

    /**
     * Properties of entity ActionEntityGdBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property GtdState = new Property(1, Integer.class, "gtdState", false, "GTD_STATE");
        public final static Property Title = new Property(2, String.class, "title", false, "TITLE");
        public final static Property Value = new Property(3, String.class, "value", false, "VALUE");
        public final static Property AttachNum = new Property(4, int.class, "attachNum", false, "ATTACH_NUM");
        public final static Property What = new Property(5, String.class, "what", false, "WHAT");
        public final static Property When = new Property(6, String.class, "when", false, "WHEN");
        public final static Property Who = new Property(7, String.class, "who", false, "WHO");
        public final static Property Where = new Property(8, String.class, "where", false, "WHERE");
        public final static Property Zygote = new Property(9, String.class, "zygote", false, "ZYGOTE");
        public final static Property TaskId = new Property(10, long.class, "taskId", false, "TASK_ID");
    }

    private DaoSession daoSession;

    private final GtdStateConverter gtdStateConverter = new GtdStateConverter();
    private final DateTimeTypeConverter whenConverter = new DateTimeTypeConverter();

    public ActionEntityGdBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ActionEntityGdBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ACTION_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"GTD_STATE\" INTEGER," + // 1: gtdState
                "\"TITLE\" TEXT," + // 2: title
                "\"VALUE\" TEXT," + // 3: value
                "\"ATTACH_NUM\" INTEGER NOT NULL ," + // 4: attachNum
                "\"WHAT\" TEXT," + // 5: what
                "\"WHEN\" TEXT," + // 6: when
                "\"WHO\" TEXT," + // 7: who
                "\"WHERE\" TEXT," + // 8: where
                "\"ZYGOTE\" TEXT," + // 9: zygote
                "\"TASK_ID\" INTEGER NOT NULL );"); // 10: taskId
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_ACTION_ENTITY_TITLE ON \"ACTION_ENTITY\"" +
                " (\"TITLE\" ASC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ACTION_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ActionEntityGdBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        GtdState gtdState = entity.getGtdState();
        if (gtdState != null) {
            stmt.bindLong(2, gtdStateConverter.convertToDatabaseValue(gtdState));
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(4, value);
        }
        stmt.bindLong(5, entity.getAttachNum());
 
        String what = entity.getWhat();
        if (what != null) {
            stmt.bindString(6, what);
        }
 
        DateTime when = entity.getWhen();
        if (when != null) {
            stmt.bindString(7, whenConverter.convertToDatabaseValue(when));
        }
 
        String who = entity.getWho();
        if (who != null) {
            stmt.bindString(8, who);
        }
 
        String where = entity.getWhere();
        if (where != null) {
            stmt.bindString(9, where);
        }
 
        String zygote = entity.getZygote();
        if (zygote != null) {
            stmt.bindString(10, zygote);
        }
        stmt.bindLong(11, entity.getTaskId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ActionEntityGdBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        GtdState gtdState = entity.getGtdState();
        if (gtdState != null) {
            stmt.bindLong(2, gtdStateConverter.convertToDatabaseValue(gtdState));
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(3, title);
        }
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(4, value);
        }
        stmt.bindLong(5, entity.getAttachNum());
 
        String what = entity.getWhat();
        if (what != null) {
            stmt.bindString(6, what);
        }
 
        DateTime when = entity.getWhen();
        if (when != null) {
            stmt.bindString(7, whenConverter.convertToDatabaseValue(when));
        }
 
        String who = entity.getWho();
        if (who != null) {
            stmt.bindString(8, who);
        }
 
        String where = entity.getWhere();
        if (where != null) {
            stmt.bindString(9, where);
        }
 
        String zygote = entity.getZygote();
        if (zygote != null) {
            stmt.bindString(10, zygote);
        }
        stmt.bindLong(11, entity.getTaskId());
    }

    @Override
    protected final void attachEntity(ActionEntityGdBean entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public ActionEntityGdBean readEntity(Cursor cursor, int offset) {
        ActionEntityGdBean entity = new ActionEntityGdBean( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : gtdStateConverter.convertToEntityProperty(cursor.getInt(offset + 1)), // gtdState
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // title
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // value
            cursor.getInt(offset + 4), // attachNum
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // what
            cursor.isNull(offset + 6) ? null : whenConverter.convertToEntityProperty(cursor.getString(offset + 6)), // when
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // who
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // where
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // zygote
            cursor.getLong(offset + 10) // taskId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ActionEntityGdBean entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setGtdState(cursor.isNull(offset + 1) ? null : gtdStateConverter.convertToEntityProperty(cursor.getInt(offset + 1)));
        entity.setTitle(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setValue(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAttachNum(cursor.getInt(offset + 4));
        entity.setWhat(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setWhen(cursor.isNull(offset + 6) ? null : whenConverter.convertToEntityProperty(cursor.getString(offset + 6)));
        entity.setWho(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setWhere(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setZygote(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setTaskId(cursor.getLong(offset + 10));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ActionEntityGdBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ActionEntityGdBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ActionEntityGdBean entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getTaskEntityGdBeanDao().getAllColumns());
            builder.append(" FROM ACTION_ENTITY T");
            builder.append(" LEFT JOIN TASK_ENTITY T0 ON T.\"TASK_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected ActionEntityGdBean loadCurrentDeep(Cursor cursor, boolean lock) {
        ActionEntityGdBean entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        TaskEntityGdBean task = loadCurrentOther(daoSession.getTaskEntityGdBeanDao(), cursor, offset);
         if(task != null) {
            entity.setTask(task);
        }

        return entity;    
    }

    public ActionEntityGdBean loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<ActionEntityGdBean> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<ActionEntityGdBean> list = new ArrayList<ActionEntityGdBean>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<ActionEntityGdBean> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<ActionEntityGdBean> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
