package ahtewlg7.utimer.enumtype;

/**
 * Created by lw on 2017/11/1.
 */

public enum GtdErrCode {
    ERR_ACTION_CANCEL,
    ERR_STATE_NULL,
    ERR_GTDENTITY_NULL,
    ERR_INCOMING_DISABLE,
    ERR_INCOMING_STEP_NULL,
    ERR_MATERIAL_NULL,
    ERR_WEEK_PREVIEW_DISABLE,
    ERR_WEEK_PREVIEW_DUPLICATE,
    ERR_PROJECT_NULL,
    ERR_PROJECT_PURPOSE_NULL,
    ERR_PROJECT_PRICIPLE_NULL,
    ERR_PROJECT_ENVISION_NULL,
    ERR_PROJECT_STEP_NULL,
    ERR_TASK_ENTITY_NULL,
    ERR_TASK_STEP_NULL,
    ERR_TASK_STEP_UNDONE,
    ERR_TASK_HOLDED,
    ERR_TASK_DONE,
    ERR_TRASH_DISABLE,
    ERR_UNTRASH_DISABLE,
    ERR_DELETE_UNTRASHED,
    ;
}
